"""
Django settings for bibliotheque_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-m6h3od&vzo7)i3vj1ol28eu54^g!$$nzdww$&+ut#=i9d5t64x')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,web-production-f8b47.up.railway.app').split(',')

# Configuration CSRF pour Railway
CSRF_TRUSTED_ORIGINS = ['https://web-production-f8b47.up.railway.app', 'http://web-production-f8b47.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Packages tiers
    'rest_framework',      # Django REST Framework
    'django_filters',      # Filtres avancés
    'jazzmin',             # Thème admin moderne
    # Notre application
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bibliotheque_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bibliotheque_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration pour Railway (PostgreSQL en production)
# Utiliser PostgreSQL seulement si toutes les variables sont disponibles
if all(os.environ.get(key) for key in ['PGDATABASE', 'PGUSER', 'PGPASSWORD', 'PGHOST', 'PGPORT']):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PGDATABASE'),
            'USER': os.environ.get('PGUSER'),
            'PASSWORD': os.environ.get('PGPASSWORD'),
            'HOST': os.environ.get('PGHOST'),
            'PORT': os.environ.get('PGPORT'),
        }
    }
else:
    # Configuration locale/Build (SQLite pour développement et build)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuration Jazzmin - Thème admin moderne
JAZZMIN_SETTINGS = {
    # Titre et branding
    'title': 'Bibliothèque API',
    'header_title': 'Bibliothèque API',
    'copyright': 'Bibliothèque API © 2024',
    'logo': 'fa-book',
    'logo_name': True,
    'welcome_sign': True,
    
    # Thème
    'theme': 'dark',
    'css': {
        'font_family': 'Roboto, sans-serif',
        'header_background': '#1a1a2e',
        'sidebar_background': '#16213e',
        'accent': '#e94560',
    },
    
    # Navigation
    'navigation': {
        'custom_links': [
            {
                'name': 'API Documentation',
                'url': '/api/',
                'icon': 'fa-code',
                'new_window': False,
            },
        ],
    },
    
    # Menu personnalisé
    'menu': [
        {
            'label': 'Gestion des Livres',
            'items': [
                {
                    'model': 'api.Livre',
                    'label': 'Livres',
                    'icon': 'fa-book',
                },
                {
                    'model': 'api.Auteur',
                    'label': 'Auteurs',
                    'icon': 'fa-user-edit',
                },
                {
                    'model': 'api.Tag',
                    'label': 'Tags',
                    'icon': 'fa-tags',
                },
            ],
        },
        {
            'label': 'Gestion des Emprunts',
            'items': [
                {
                    'model': 'api.Emprunt',
                    'label': 'Emprunts',
                    'icon': 'fa-hand-holding',
                },
                {
                    'model': 'api.ProfilLecteur',
                    'label': 'Lecteurs',
                    'icon': 'fa-users',
                },
            ],
        },
        {
            'label': 'Administration',
            'items': [
                {
                    'app': 'auth',
                    'label': 'Utilisateurs',
                    'icon': 'fa-user-shield',
                },
            ],
        },
    ],
    
    # Options avancées
    'language_selector': True,
    'hide_model_audit_log': True,
    'show_ui_builder': False,
    'action_menu': [
        'add',
        'export',
        'delete',
    ],
    
    # Dashboard
    'dashboard': {
        'welcome_sign': True,
        'recent_actions': {
            'enabled': True,
            'limit': 5,
        },
    },
}

# Configuration REST Framework
REST_FRAMEWORK = {
    # Classe d'authentification par défaut
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # Permissions par défaut
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # Pagination par défaut
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Filtres
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Configuration JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Token d'accès
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Token de renouvellement
    'AUTH_HEADER_TYPES': ('Bearer',),  # Format: Authorization: Bearer <token>
}
